version: '3.3'


services:
  db:
    image: postgres
    restart: always
    container_name: "movieapi_db"
    env_file:
      - ./internal/config/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data2/pgdata
      - ./config:/app/config
    networks:
      - movieapi
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=movie_db
      - POSTGRES_PORT=5432


  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: movieapi
    container_name: "movieapi_api"
    restart: always
    networks:
      - movieapi
    ports:
      - "8081:8081"
    environment:
      - DB_SOURCE=:movieapi_db//postgres:password@postgres:5432/movie_db?sslmode=disable
    depends_on:
      - db
    volumes:
      - ./config:/app/internal/config
    command: ["/app/main"]

  redis:
    image: redis
    restart: always
    container_name: "movieapi_redis"
    networks:
      - movieapi
    ports:
      - "6379:6379"

networks:
  movieapi:
    driver: bridge